# Generated by Django 4.2.7 on 2023-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvs_nomenclature', models.CharField(max_length=100, unique=True)),
                ('variant_effect', models.CharField(max_length=50)),
                ('annotation', models.TextField()),
            ],
        ),
    ]
