# Generated by Django 4.2.7 on 2023-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haemonc_django_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='hgvs_nomenclature',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_effect',
            field=models.CharField(max_length=20),
        ),
    ]
