# Generated by Django 4.2.7 on 2024-03-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haemonc_django_frontend', '0003_varianten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
